### ISSUE TITLE
Crash in PFUIImageView

### ISSUE THREAD

**Issue by Vortec4800** [ParsePlatform/ParseUI-iOS#188]
I get a pretty regular crash on line 117 of PFUIImageView where the image data is being loaded:

```objc
    [_file getDataInBackgroundWithBlock:^(NSData *data, NSError *error) {
        if (error) {
            if (completion) {
                dispatch_async(dispatch_get_main_queue(), ^{
                    completion(nil, error);
                });
            }
            return;
        }

        // We dispatch to a background queue to offload the work to decode data into image
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
            UIImage *image = [UIImage imageWithData:data];
            if (!image) {
                if (completion) {
                    NSError *invalidDataError = [NSError errorWithDomain:PFParseErrorDomain
                                                                    code:kPFErrorInvalidImageData
                                                                userInfo:nil];
                    dispatch_async(dispatch_get_main_queue(), ^{
                        completion(nil, invalidDataError);
                    });
                }
                return;
            }

            dispatch_async(dispatch_get_main_queue(), ^{
                // check if a latter issued loadInBackground has not replaced the file being loaded
                if (file == _file) {
                    self.image = image;
                }

                if (completion) {
                    completion(image, nil);
                }
            });

            if (url) {
                // We always want to store the image in the cache.
                // In previous checks we've verified neither key nor value is nil.
                [[PFImageCache sharedCache] setImage:image forURL:url];
            }
        });
    } progressBlock:progressBlock];
```

The specific line in question is `UIImage *image = [UIImage imageWithData:data];` and when the crash occurs, I get this message in the console: `malloc: *** error for object 0x7fed2510b080: pointer being freed was not allocated`.

It seems like perhaps the data is getting released before it can be loaded. Has anyone else run in to this?

**Comment by ev0lution** [comment]
+1, I've just encountered this issue. Did you ever come across a fix for it?

My scenario is that a few table view cells contain PFImageViews and they're loading the same PFFile at the same time. About a third of the time, the app will crash with this error. 

I have enabled Address Sanitizer and it generated this report when it crashed (same line as above, with the error "attempt to deallocate a freed object"):

    =================================================================
    ==34553==ERROR: AddressSanitizer: attempting double-free on 0x6070000319c0 in thread T6:
        #0 0x1049bc614 in __asan_mz_free (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.asan_iossim_dynamic.dylib+0x41614)
        #1 0x108dad21a in __CFBasicHashAddValue (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation+0x921a)
        #2 0x108dabc6c in CFDictionarySetValue (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation+0x7c6c)
        #3 0x10796842d in _UITraitCollectionCacheForBuiltinStorage (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0xa8742d)
        #4 0x10796a75d in +[UITraitCollection traitCollectionWithDisplayScale:] (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0xa8975d)
        #5 0x106f63c8d in -[UIImage(UIImagePrivate) _initWithData:preserveScale:cache:] (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0x82c8d)
        #6 0x106f5efd4 in +[UIImage imageWithData:] (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0x7dfd4)
        #7 0x10460eaac in __46-[PFImageView loadInBackground:progressBlock:]_block_invoke32 PFImageView.m:117
        #8 0x1049ba8b3 in __wrap_dispatch_async_block_invoke (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.asan_iossim_dynamic.dylib+0x3f8b3)
        #9 0x109431e5c in _dispatch_call_block_and_release (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0x1e5c)
        #10 0x10945249a in _dispatch_client_callout (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0x2249a)
        #11 0x10943abee in _dispatch_root_queue_drain (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0xabee)
        #12 0x10943a4c4 in _dispatch_worker_thread3 (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0xa4c4)
        #13 0x10978a4f1 in _pthread_wqthread (/usr/lib/system/libsystem_pthread.dylib+0x34f1)
        #14 0x109788374 in start_wqthread (/usr/lib/system/libsystem_pthread.dylib+0x1374)

    0x6070000319c0 is located 0 bytes inside of 72-byte region [0x6070000319c0,0x607000031a08)
    freed by thread T4 here:
        #0 0x1049bc614 in __asan_mz_free (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.asan_iossim_dynamic.dylib+0x41614)
        #1 0x108dad21a in __CFBasicHashAddValue (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation+0x921a)
        #2 0x108dabc6c in CFDictionarySetValue (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation+0x7c6c)
        #3 0x10796842d in _UITraitCollectionCacheForBuiltinStorage (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0xa8742d)
        #4 0x10796a75d in +[UITraitCollection traitCollectionWithDisplayScale:] (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0xa8975d)
        #5 0x106f63c8d in -[UIImage(UIImagePrivate) _initWithData:preserveScale:cache:] (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0x82c8d)
        #6 0x106f5efd4 in +[UIImage imageWithData:] (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0x7dfd4)
        #7 0x10460eaac in __46-[PFImageView loadInBackground:progressBlock:]_block_invoke32 PFImageView.m:117
        #8 0x1049ba8b3 in __wrap_dispatch_async_block_invoke (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.asan_iossim_dynamic.dylib+0x3f8b3)
        #9 0x109431e5c in _dispatch_call_block_and_release (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0x1e5c)
        #10 0x10945249a in _dispatch_client_callout (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0x2249a)
        #11 0x10943abee in _dispatch_root_queue_drain (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0xabee)
        #12 0x10943a4c4 in _dispatch_worker_thread3 (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0xa4c4)
        #13 0x10978a4f1 in _pthread_wqthread (/usr/lib/system/libsystem_pthread.dylib+0x34f1)
        #14 0x109788374 in start_wqthread (/usr/lib/system/libsystem_pthread.dylib+0x1374)

    previously allocated by thread T5 here:
        #0 0x1049bc0ed in __asan_mz_malloc (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.asan_iossim_dynamic.dylib+0x410ed)
        #1 0x10964a36c in malloc_zone_malloc (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/libsystem_malloc.dylib+0x1136c)
        #2 0x107968373 in _UIBuiltinTraitStorageRetain (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0xa87373)
        #3 0x108dad0eb in __CFBasicHashAddValue (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation+0x90eb)
        #4 0x108dabc6c in CFDictionarySetValue (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation+0x7c6c)
        #5 0x10796842d in _UITraitCollectionCacheForBuiltinStorage (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0xa8742d)
        #6 0x10796a75d in +[UITraitCollection traitCollectionWithDisplayScale:] (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0xa8975d)
        #7 0x106f63c8d in -[UIImage(UIImagePrivate) _initWithData:preserveScale:cache:] (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0x82c8d)
        #8 0x106f5efd4 in +[UIImage imageWithData:] (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit+0x7dfd4)
        #9 0x10460eaac in __46-[PFImageView loadInBackground:progressBlock:]_block_invoke32 PFImageView.m:117
        #10 0x1049ba8b3 in __wrap_dispatch_async_block_invoke (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.asan_iossim_dynamic.dylib+0x3f8b3)
        #11 0x109431e5c in _dispatch_call_block_and_release (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0x1e5c)
        #12 0x10945249a in _dispatch_client_callout (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0x2249a)
        #13 0x10943abee in _dispatch_root_queue_drain (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0xabee)
        #14 0x10943a4c4 in _dispatch_worker_thread3 (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib+0xa4c4)
        #15 0x10978a4f1 in _pthread_wqthread (/usr/lib/system/libsystem_pthread.dylib+0x34f1)
        #16 0x109788374 in start_wqthread (/usr/lib/system/libsystem_pthread.dylib+0x1374)

    Thread T6 created by T0 here:
        <empty stack>

    Thread T4 created by T3 here:
        <empty stack>

    Thread T3 created by T0 here:
        <empty stack>

    Thread T5 created by T2 here:
        <empty stack>

    Thread T2 created by T0 here:
        <empty stack>

    SUMMARY: AddressSanitizer: double-free ??:0 __asan_mz_free
    ==34553==ABORTING

**Comment by Vortec4800** [comment]
I was not able to fix this issue, no. My (annoying) solution has been to run the app on my actual device for development where it doesn't crash. This of course takes much longer, but I haven't tried to dig in deeper to figure out what the actual problem is.

**Comment by boreys** [comment]
I am facing the same issue. Anyone found a good solution?

**Comment by ev0lution** [comment]
I ended up replacing PFImageView with SDWebImage because of this issue - just feed it the URL of the PFFile.
